import { createClient } from '@supabase/supabase-js';

const url = import.meta.env.VITE_SUPABASE_URL;
const anonKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!url || !anonKey) {
  throw new Error(
    'Missing Supabase env vars. Expected VITE_SUPABASE_URL and ' +
      'VITE_SUPABASE_PUBLISHABLE_KEY in .env.local (auto-generated by ' +
      'post-create.sh on devcontainer rebuild).',
  );
}

export const supabase = createClient(url, anonKey);
